import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google"

const inter = Inter({
  subsets:['latin']
})

export const metadata: Metadata = {
  title: "Multi-step Register",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased bg-[#121826] overflow-hidden w-full h-screen `}
      >
        {children}
      </body>
    </html>
  );
}
